name: test actions github

on:
  push:
  workflow_dispatch:
    inputs:
      CORE_VERSION:
        description: 'CORE_VERSION'
        required: false
        default: '0.0.1'
        
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:            
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Prepare varibles
      id: varibles_prepare
      run: |      
        cd ${{ github.workspace }}
        
        RESULT=$(grep "versionName =" ${{ github.workspace }}/build.gradle.kts)
        RESULT=${RESULT:`expr index "$RESULT" \"`}
        RESULT=${RESULT::`expr index "$RESULT" \"`-1}
        echo "VERSION_CODE_BUILD_VARIABLE=$RESULT" >> $GITHUB_OUTPUT
        echo "versionCode:$RESULT"
        
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"                          
        echo "BUILD_NUMBER_ENV:${{ env.BUILD_NUMBER_ENV }}"        
        
        echo "BUILD_NUMBER=$(`expr ${{ vars.BUILD_NUMBER }} + 1`)" >> $GITHUB_OUTPUT 
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"
      env:
        BUILD_NUMBER_ENV: ${{ vars.BUILD_NUMBER }}
        
    - name: check varibles
      run: |      
        cd ${{ github.workspace }}
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"                   
        echo "BUILD_NUMBER_ENV:${{ env.BUILD_NUMBER_ENV }}"
        echo "steps.BUILD_NUMBER:${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}
        gh variable set BUILD_NUMBER --body ${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}
      env:
        BUILD_NUMBER_ENV: ${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}