name: test actions github

on:
  push:
  workflow_dispatch:
    inputs:
      CORE_VERSION:
        description: 'CORE_VERSION'
        required: false
        default: '0.0.1'
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:            
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare varibles
      run: |      
        cd ${{ github.workspace }}
        
        RESULT=$(grep "versionName =" ${{ github.workspace }}/build.gradle.kts)
        RESULT=${RESULT:`expr index "$RESULT" \"`}
        RESULT=${RESULT::`expr index "$RESULT" \"`-1}
        echo "VERSION_CODE_BUILD_VARIABLE=$RESULT" >> $GITHUB_OUTPUT
        echo "versionCode:$RESULT"
        
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"