name: test actions github

on:
  push:
  workflow_dispatch:
    inputs:
      CORE_VERSION:
        description: 'CORE_VERSION'
        required: false
        default: '0.0.1'
        
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:            
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Prepare varibles
      id: varibles_prepare
      run: |      
        cd ${{ github.workspace }}
        
        RESULT=$(grep "versionName =" ${{ github.workspace }}/build.gradle.kts)
        RESULT=${RESULT:`expr index "$RESULT" \"`}
        RESULT=${RESULT::`expr index "$RESULT" \"`-1}
        echo "VERSION_CODE_BUILD_VARIABLE=$RESULT" >> $GITHUB_OUTPUT
        echo "versionCode:$RESULT"
        
        echo "run_number:${{ github.run_number }}"   
        echo "run_number=${{ github.run_number }}" >> $GITHUB_OUTPUT
        
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"                          
        echo "BUILD_NUMBER_ENV:${{ env.BUILD_NUMBER_ENV }}"        
        
        echo "BUILD_NUMBER=$((${{ vars.BUILD_NUMBER }} + 1))" >> $GITHUB_OUTPUT 
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"
        
        MESSAGE="🚀 У нас новый commit для *Android*\nАвтор:"
        echo $MESSAGE
          
        curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"$MESSAGE\", \"parse_mode\": \"Markdown\"}" \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage > ${{ github.workspace }}/telegram_send_output.txt
        
        MESSAGE_ID=$(grep -oP 'message_id\":\d+' telegram_send_output.txt)
        MESSAGE_ID=${MESSAGE_ID:`expr index "$MESSAGE_ID" \:`}    
        echo "MESSAGE_ID=$MESSAGE_ID"
        echo "MESSAGE_ID=$MESSAGE_ID" >> $GITHUB_OUTPUT 
        
        ls ${{ github.workspace }}    
        
      env:
        BUILD_NUMBER_ENV: ${{ vars.BUILD_NUMBER }}
        
    - name: check varibles
      run: |      
        cd ${{ github.workspace }}
        echo "BUILD_NUMBER:${{ vars.BUILD_NUMBER }}"                   
        echo "BUILD_NUMBER_ENV:${{ env.BUILD_NUMBER_ENV }}"
        echo "steps.BUILD_NUMBER:${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}"
        gh variable set BUILD_NUMBER --body "${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}"
        
        echo "env.RUN_NUMBER_ENV:${{ env.RUN_NUMBER_ENV }}"
        
        MESSAGE="🚀 У нас новый commit для *Android*\nАвтор:\nСборка завершена"
        echo $MESSAGE
        
        curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"${{ secrets.TELEGRAM_CHAT_ID }}\", \"text\": \"$MESSAGE\", \"parse_mode\": \"Markdown\"}", \"message_id\": \"${{steps.varibles_prepare.outputs.MESSAGE_ID}}\" \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/editMessageText
        
      env:
        BUILD_NUMBER_ENV: ${{ steps.varibles_prepare.outputs.BUILD_NUMBER }}
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        RUN_NUMBER_ENV: ${{ steps.varibles_prepare.outputs.run_number }}_(123)